.set NUMNOTAS, 70
notaFS:
	.word   LA
	.word   LA
	.word   LA
	.word   FA
	.word   DOH

	.word   LA
	.word   FA
	.word   DOH
	.word   LA

	.word   MIH
	.word   MIH
	.word   MIH
	.word   FAH
	.word   DOH

	.word   SOLs
	.word   FA
	.word   DOH
	.word   LA

	.word   LAH
	.word   LA
	.word   LA
	.word   LAH
	.word   SOLHs
	.word   SOLH

	.word   FAHs
	.word   FAH
	.word   FAHs
	.word   SILEN
	.word   LAs
	.word   REHs
	.word   REH
	.word   DOHs

	.word   DOH
	.word   SI
	.word   DOH
	.word   SILEN
	.word   FA
	.word SOLs
	.word FA
	.word SOLs

	.word DOH
	.word LA
	.word DOH
	.word MIH

	.word   LAH
	.word   LA
	.word   LA
	.word   LAH
	.word   SOLHs
	.word   SOLH


	.word   FAHs
	.word   FAH
	.word   FAHs
	.word   SILEN
	.word   LAs
	.word   REHs
	.word   REH
	.word   DOHs

	.word   DOH
	.word   SI
	.word   DOH
	.word   SILEN
	.word   FA
	.word SOLs
	.word FA
	.word SOLs

	.word   LA
	.word   FA
	.word   DOH
	.word   LA


duratFS:
	.word NG
	.word NG
	.word NG
	.word CORP
	.word FUS

	.word NG
	.word CORP
	.word FUS
	.word BL

	.word NG
	.word NG
	.word NG
	.word CORP
	.word FUS

	.word NG
	.word CORP
	.word FUS
	.word BL

	.word NG
	.word CORP
	.word FUS
	.word NG
	.word CORP
	.word FUS

	.word FUS
	.word FUS
	.word COR
	.word COR   	@SILEN
	.word COR
	.word NG
	.word CORP
	.word FUS

	.word FUS
	.word FUS
	.word COR
	.word COR      @SILEN
	.word COR
	.word NG
	.word CORP
	.word FUS

	.word NG
	.word CORP
	.word FUS
	.word BL

	.word NG
	.word CORP
	.word FUS
	.word NG
	.word CORP
	.word FUS

	.word FUS
	.word FUS
	.word COR
	.word COR   	@SILEN
	.word COR
	.word NG
	.word CORP
	.word FUS

	.word FUS
	.word FUS
	.word COR
	.word COR   	@SILEN
	.word COR
	.word NG
	.word CORP
	.word FUS

	.word NG
	.word CORP
	.word FUS
	.word BL
