
@ DGCFAd
@ 170bpm
gjrNotas:
    .word MI    @D2
    .word LAs   @G3
    .word MI    @D2
    .word LA    @G2
    .word LA    @G2 _
    .word MI    @D2

    .word LAs   @G3
    .word MI    @D2
    .word DOH   @G5
    .word DOH   @G5 _
    .word MI    @D2
    .word LAs   @G3 _>
    .word LA    @G2 <_

    .word RE    @D0
    .word LA    @G2
    .word RE    @D0
    .word SOL   @D5
    .word SOL   @D5 _
    .word RE    @D0

    .word FA    @D3
    .word RE    @D0
    .word MI    @D2
    .word MI    @D2 _
    .word RE    @D0
    .word FA    @D3

    @@

    .word MI    @D2
    .word LAs   @G3
    .word MI    @D2
    .word LA    @G2
    .word LA    @G2 _
    .word MI    @D2

    .word LAs   @G3
    .word MI    @D2
    .word DOH   @G5
    .word DOH   @G5 _
    .word MI    @D2
    .word LAs   @G3 _>
    .word LA    @G2 <_

    .word RE    @D0
    .word LA    @G2
    .word RE    @D0
    .word SOL   @D5
    .word SOL   @D5 _
    .word RE    @D0

    .word FA    @D3
    .word RE    @D0
    .word MI    @D2
    .word MI    @D2 _
    .word RE    @D0
    .word MI    @D2
    .word FA    @D3

    @@

    .word MI    @D2
    .word LAs   @G3
    .word MI    @D2
    .word LA    @G2
    .word LA    @G2 _
    .word MI    @D2

    .word LAs   @G3
    .word MI    @D2
    .word DOH   @G5
    .word DOH   @G5 _
    .word MI    @D2
    .word LAs   @G3 _>
    .word LA    @G2 <_

    .word RE    @D0
    .word LA    @G2
    .word RE    @D0
    .word SOL   @D5
    .word SOL   @D5 _
    .word RE    @D0

    .word FA    @D3
    .word RE    @D0
    .word MI    @D2
    .word MI    @D2 _
    .word RE    @D0
    .word FA    @D3

    @@

    .word MI    @D2
    .word LAs   @G3
    .word MI    @D2
    .word LA    @G2
    .word LA    @G2 _
    .word MI    @D2

    .word LAs   @G3
    .word MI    @D2
    .word DOH   @G5
    .word DOH   @G5 _
    .word MI    @D2
    .word LAs   @G3 _>
    .word LA    @G2 <_

    .word RE    @D0
    .word LA    @G2
    .word RE    @D0
    .word LA    @D7
    .word SOL   @D5 _
    .word RE    @D0

    .word SOL   @D5
    .word FA    @D3
    .word RE    @D0
    .word FA    @D3 _
    .word MI    @D2
    .word RE    @D0
    .word MI    @D2
    .word FA    @D3



.set NEGRA,     352941
.set CORCHEA,   176471
gjrDurat:
    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word NEGRA

    @@

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    @@

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word NEGRA

    @@

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word NEGRA
    .word NEGRA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
