
@ BEADF#b
@ 189bpm
fkNotas:
    .word FAHs  @7
    .word SI    @0
    .word SI    @0
    .word MIH   @5
    .word SI    @0
    .word SI    @0
    .word REH   @3
    .word SI    @0

    .word SI    @0
    .word MIH   @5
    .word SI    @0
    .word SI    @0
    .word REH   @3
    .word SI    @0
    .word DOHs  @2
    .word SI    @0



.set NEGRA,     317460
.set CORCHEA,   158730
fkDurat:
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA

    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
    .word CORCHEA
