@ 27 notas
@ EADGBe
.set SEMIC, 103448
mpeNotas:
    .word SIH @0 19
    .word MIH @0 12
    .word REH @0 10
    .word MIH @0 12
    .word SOLH @1 20
    .word SI @1 12
    .word LA @1 10
    .word SI @1 12
    .word MIH @1 17 == @0 12
    .word SI @1 12
    .word LA @1 10
    .word SI @1 12
    .word SOLH @0 15
    .word MIH @0 12
    .word REH @0 10
    .word MIH @0 12
    .word FAHs @1 19
    .word SI @1 12
    .word LA @1 10
    .word SI @1 12
    .word REH @1 15
    .word SI @1 12
    .word LA @1 10
    .word SI @1 12
    .word MIH @1 17 == @0 12
    .word SI @1 12
    .word LA @1 10
    .word SI @1 12
    .word FAHs @1 19
    .word SI @1 12
    .word LA @1 10
    .word SI @1 12
mpeDurat:
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
    .word SEMIC
