/* frecuencias */


.set RE, 1703
.set MI, 1517
.set FA, 1433     @ Retardo para nota Fa = F
.set SOL, 1276
.set SOLs, 1204   @ Retardo para nota SOLs = Gs
.set LA, 1136     @ Retardo para nota La = A
.set LAs, 1072
.set SI, 1012

.set DOH, 956     @ Retardo para nota DoH = cH
.set DOHs, 902
.set REH, 851
.set REHs, 803

.set MIH, 758     @ Retardo para nota MIH = eH
.set FAH, 716     @ Retardo para nota FAH = FH
.set FAHs, 676
.set SOLH, 638
.set SOLHs, 602
.set LAH, 568
.set LAHs, 536
.set SIH, 507

.set DOHH, 478



.set SILEN, 555  @silencio


/* duraciones */

.set NG,  500000
.set CORP,  375000
.set COR,    250000
.set FUS,   125000
.set BL, 1000000
