@ DGCFAd
.set SEMIC, 187500
.set CORC,  375000
.set FUSA,  93750
.set CORCP, 468750
.set NEGRA, 750000
stbNotas:
    .word SOL @3 7
    .word DOH @2 7
    .word REH @2 9
    .word REHs @2 10
    .word DOH @2 7
    .word SOLH @1 10
    .word FAH @1 8
    .word REHs @2 10
    .word REH  @2 9
    .word DOH  @3 11
    .word LAs @3 10
    .word DOH @2 7
    .word REH @2 9
    .word REH @2 9
    .word REHs @2 10
    .word REH @2 9
    .word DOH @2 7
    .word LAs @2 5
    .word LAs @2 5
    .word DOH @2 7
    .word SOL @2 2
    .word SOL @3 7
    .word DOH @2 7
    .word REH @2 9
    .word REHs @2 10
    .word DOH @2 7
    .word SOLH @1 10
    .word FAH @1 8
    .word REHs @2 10
    .word REH  @2 9
    .word DOH @2 7
    .word REHs @2 10
    .word LAs @2 5
    .word DOH @2 7
    .word REH @2 9
    .word REH @2 9
    .word REHs @2 10
    .word REH @2 9
    .word DOH @2 7
    .word LAs @2 5
    .word FAH @1 8
    .word SOLH @1 10
    .word REH @2 9
    .word REHs @2 10

stbDurat:
    .word SEMIC @3 7
    .word SEMIC @2 7
    .word SEMIC @2 9
    .word SEMIC @2 10
    .word SEMIC @2 7
    .word SEMIC @1 10
    .word CORC @1 8
    .word CORC @2 10
    .word CORC  @2 9
    .word CORC  @3 11
    .word NEGRA@3 10
    .word SEMIC @2 7
    .word SEMIC @2 9
    .word SEMIC @2 9
    .word FUSA @2 10
    .word FUSA @2 9
    .word SEMIC @2 7
    .word SEMIC @2 5
    .word CORC @2 5
    .word CORC @2 7
    .word NEGRA @2 2
@ REVISAR
    .word SEMIC @3 7
    .word SEMIC @2 7
    .word SEMIC @2 9
    .word SEMIC @2 10
    .word SEMIC @2 7
    .word SEMIC @1 10
    .word CORC @1 8
    .word CORC @2 10
    .word CORC  @2 9
    .word CORC  @3 11
    .word NEGRA @3 10
    .word SEMIC @2 5
    .word SEMIC @2 7
    .word SEMIC @2 9
    .word SEMIC @2 9
    .word FUSA @2 10
    .word FUSA @2 9
    .word SEMIC @2 7
    .word SEMIC @2 5
    .word CORC @1 8
    .word CORC @1 10
    .word CORC @2 9
    .word CORC @2 10
