.set NUMNOTAS, 128
@ DGCFAd
wtsNotas:
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word DOHH  @10
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAHs  @8
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN

    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word FAH   @3
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word FAH   @3
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word FAH   @3
    .word SILEN
    .word REH   @0
    .word SILEN

    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN
    .word DOHH  @10
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAHs  @8
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word LAH   @7
    .word SILEN
    .word REH   @0
    .word SILEN

    .word SOLH  @5
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word SOLH  @5
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word SOLH  @5
    .word SILEN
    .word REH   @0
    .word SILEN
    .word MIH   @2
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word MIH   @2
    .word SILEN
    .word REH   @0
    .word SILEN
    .word REH   @0
    .word SILEN
    .word MIH   @2
    .word SILEN
    .word REH   @0
    .word SILEN


.set D1, 125000
.set D2, 62500
wtsDurat:
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2

    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2

    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2

    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
    .word D1
    .word D2
